- velociraptor/fitting_formulae/smhmr.py
- velociraptor/observations/objects.py
- Behroozi 2019 SMHM fitting function (for all z) has been added to VR
- Redshifts will now show up in obs-data curves' labels
Example of the new stellar mass halo mass plot:
> Behroozi 2019 SMHM data (fit for all z)

- velociraptor/__init__.py
- velociraptor/catalogue/registration.py
**Add stellar birth density registration to velociraptor**
New lines in the velociraptor config:
```
Star_internal_property_names=BirthDensities,BirthDensities,BirthDensities,
Star_internal_property_input_output_unit_conversion_factors=1.0e10,1.0e10,1.0e10,
Star_internal_property_calculation_type=max,min,average,
Star_internal_property_output_units=solar_mass/MPc3,solar_mass/MPc3,solar_mass/MPc3,
```
> Add stellar birth density registration

- velociraptor/tools/adaptive.py
- velociraptor/tools/mass_functions.py
Hi @JBorrow, I've found one more bug.
This one is particularly annoying because it makes the whole pipeline crash, not just one plot.
**Explanation**
The bug occurs in the plots with `adaptive binning` in the case that we want to **stretch** the previous bin to cover the remaining data points. The latter will err if we have just one bin in total (i.e. in this case there's no previous bin because the total number of bins is one)
**Backtrace**
```
Traceback (most recent call last):
File "/home/evgenii/anaconda3/bin/swift-pipeline", line 241, in <module>
directory=args.output, file_extension=PLOT_FILE_EXTENSION, debug=args.debug
File "/home/evgenii/velociraptor-python/velociraptor/autoplotter/objects.py", line 1026, in create_plots
file_extension=file_extension,
File …
```
> Bug in plots with adaptive binning

- velociraptor/autoplotter/lines.py
A tiny fix to the case whereby a plot has no data. Without this fix, in the no-data case, we may be adding quantities that have dimensions with dimensionless quantities (see the lines of code I changed to understand exactly what I mean). This makes `unyt` library unhappy.
With the fix, plots like the one below are correctly made:
> make units consistent in the case of no data

- velociraptor/autoplotter/lines.py
We have decided to highlight the additional data points in single-run plots; otherwise, they could be not visible because of the observational data plotted above
**Result:** [LINK](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/DEC2020/L006N188/NO_EOS/z0.0_2E51_FKIN03_VKICK050_BOOST01/)
> Highlight additional points in single-run plots

- velociraptor/autoplotter/compare.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/objects.py
Hi @JBorrow 
This is my first attempt to implement the arrow feature.
Below I describe
- what exactly the feature does
- what problems I encountered while implementing it, and how the problems were resolved
- Examples
<h2>Descripton</h2>
- There is a new function `highlight_data_outside_domain()` in ` autoplotter/lines.py` which compares X and Y coordinates of the additional data points to the lower and upper limits of the X and Y axes, respectively. 
- If a data point happens to lie outside the plot's domain, then an arrow is drawn. The arrow indicates where the missing point is. For a given missing data point with its Y(X) coordinate outside the Y(X)-axis range, the corresponding arrow will have the same X(Y) coordinate. If a data point lies outside both the X-axis range and Y-axis …
> Show arrows where the data is outside the plot's domain

- requirements.txt
- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/objects.py
- velociraptor/autoplotter/plot.py
- velociraptor/tools/lines.py
**Add the minimum number of additional data points to show in mean-line and median-line plots**
- We need this feature because we always want to know what the largest objects are doing. If some objects become part of median-line bins it becomes increasingly harder to tell what is going on
- I set the default value to be 10, but since we may want different numbers for different plots, I make it possible to set it for every plot through a new parameter in autoplotter's .yml config
- I don't like that the new argument first goes to `plot_line()`, then to `create_line()`, and then to `binned_median_line()`. Maybe we can shorten the path?
**Example:**
Also, **housekeeping**
- Add the missing `matplotlib` dependence in requirements.txt
- To tiny changes in `velociraptor/autoplotter/plot.py`
> Feature: add minimum number of additional data points

- velociraptor/tools/lines.py
**Fixes very annoying bug** 
The fix is not perfect, but it works. The bug has to do with empty axes labels and wrong axes limits in the case that the median/mean line arrays are **empty**
<h2>EXAMPLE 1</h2>
<h3>BEFORE THE FIX</h3>
<h3>AFTER THE FIX</h3>
<h2>EXAMPLE 2</h2>
<h3>BEFORE THE FIX</h3>
<h3>AFTER THE FIX</h3>
> Fix annoying bug with empty axes labels and wrong axes limits

- velociraptor/catalogue/registration.py
Some versions of VR add an 'index_0_' in the name here. This makes the registration robust against it
> Small change to the HI, H2 and HII registration

- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/objects.py
- velociraptor/catalogue/registration.py
implement option to exclude a structure number to complement the include option, allowing isolation of satellites 
Rebased onto https://github.com/SWIFTSIM/velociraptor-python/pull/55 , will change from draft to active status once PR55 merged.
> Exclude structure type

- velociraptor-plot
- velociraptor/__init__.py
- velociraptor/autoplotter/objects.py
- velociraptor/catalogue/catalogue.py
- velociraptor/catalogue/registration.py
Apply a global mask to `autoplotter` plots. This can be specified in the pipeline `config.yaml`, and constructed in `registration.py`. Without specification, no mask is applied. 
Changes straddle the pipeline and pipeline-configs repositories see also PRs https://github.com/SWIFTSIM/pipeline/pull/25, https://github.com/SWIFTSIM/pipeline-configs/pull/130.
> Global masking

- velociraptor/catalogue/registration.py
Add registration function for element masses contained in stars to make plots like [THIS](http://swift.dur.ac.uk/COLIBREPlots/chaikin/comparisons/HAWK/L025N376/z0.5_106c3_W_vs_WO_4xDM_PARTICLES_[106c3,129c3]/index.html#5115245619656451599)
> Register element masses in stars

- docs/source/particles_files/index.rst
- velociraptor/swift/swift.py
I found myself wanting to re-use the masking code from this package, and it made more sense for both that use-case and from a code organisation standpoint to split the calculation across two functions. The original function `to_swiftsimio_dataset` is still there for compatibility of course and simply calls the two new functions, `generate_spatial_mask` and `generate_bound_mask`.
> Split spatial masking and masking by group ID into separate functions.

- docs/source/particles_files/index.rst
- velociraptor/particles/particles.py
Since the extracted halo is actually the `halo_index`'th in the list, and not the one with unique id `halo_id`, the argument should be renamed to reflect this.
> Rename halo_id to halo_index to reflect desired input, and document.

- docs/source/basic_usage/index.rst
- docs/source/particles_files/index.rst
- velociraptor/__init__.py
- velociraptor/catalogue/catalogue.py
- velociraptor/particles/particles.py
A mask can be provided to a `VelociraptorCatalogue` on initialisation (also via `load`). The default is `Ellipsis` (`...`), resulting in the previous behaviour. If another mask is provided, it is applied while reading arrays from the catalogue and reads only the masked region. This can be used e.g. to efficiently load values for a single halo of interest.
The package under development at https://github.com/kyleaoman/swiftgalaxy will depend on this feature.
> Add ability to mask catalogue

- velociraptor-compute-box-size-correction
- velociraptor/autoplotter/box_size_correction.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/objects.py
First draft of a new mechanism to add a correction to catalogue values in pipeline plots to correct for box size effects.
The idea is that the user specifies an additional `box_size_correction` argument in the autoplotter config file, which points to a file that contains correction values (format still to be decided). This is then used to initialise an object that has a correction function that is applied to the plot data before it is plotted.
@EvgeniiChaikin I will expand on this tomorrow, but this is what I had in mind.
> Box size correction

- velociraptor/autoplotter/lines.py
`unyt.matplotlib_support` seems to be unable to deal with plots where all data values are `NaN`. You can end up in that scenario when you compute a log median line for data that only has `NaN` or `0` x values (which apparently really happens for some of the pipeline plots).
The solution is to filter out all `NaN` values before computing the median line (or any other line for that matter).
@james-trayford could you check that this fixes your issue and does not break any of the plots in the pipeline?
> Filter out NaN values when computing lines

- velociraptor/autoplotter/compare.py
This fixes a bug when running the pipeline in comparison mode: the box size correction directory was not passed on to `recreate_instances()`.
Note that the box size correction is not actually used in comparison mode, but it is hard to disable it completely.
> Also use box size correction in comparison mode

- velociraptor/catalogue/registration.py
Based on the title, this is just a merge request to also include the SNIa rates in the velociraptor library. So far they were not included, this fixes that.
> Include the SNIa rates inside the aperatures in the library

- velociraptor/autoplotter/objects.py
- velociraptor/autoplotter/plot.py
Move the creation of plt.figure ouside `scatter_x_against_y` method.
- This change was motivated by @FHusko's recent update in the colibre-pipeline (https://github.com/SWIFTSIM/pipeline-configs/pull/214). In that PR, many scripts repeat exactly the same calculations as those carried out by the `scatter_x_against_y` method. However, the `scatter_x_against_y` method in its current version cannot be simply imported and applied to Filip's plots because `scatter_x_against_y` creates its own `(fig,ax)` object.
- This PR makes `scatter_x_against_y` create and apply the scatter to the `(fig,ax)` object passed by the user as an additional function's argument, instead of creating a new `(fig,ax)`  object.
- With this update, not only the `scatter_x_against_y` method becomes compatible with Filip's …
> Move the creation of plt.figure ouside the x vs. y scatter method

- velociraptor/particles/__init__.py
- velociraptor/particles/particles.py
There were a few leftover instances of VelociraptorCatalogue that were not yet renamed to Catalogue.
The current pypi release is broken because of this, please create a new release when this is merged?
> bugfix: VelociraptorCatalogue renamed to Catalogue

- velociraptor/catalogue/translator.py
- Add stellar birth pressures to the SOAP translator file
- Inside the translator file, replace `average-of-log` with `median` for all stellar birth properties
Follows https://github.com/SWIFTSIM/SOAP/pull/62
> Update stellar birth properties in SOAP translator file

- velociraptor/observations/objects.py
This PR adds a new functionality that enables the user to indicate lower and/or upper limits of observational data.
To specify lower/upper limits, the user will need to pass one or two bool arrays to the `associate_y()` method in the conversion script that converts the data from raw to hdf5 format.
Once the raw data have been processed and saved as an hdf5 file, no further changes are required. That is: everything else in the pipeline remains the same.
**For example,**
I can modify `data/GalaxyHIMassFunction/convertJones2018.py` conversion script as
```
data = np.genfromtxt(input_filename, comments="#")
processed = ObservationalData()
comment = (
"Jones et al. (2018). Estimated for ALFALFA survey at z=0"
f"data, h-corrected for SWIFT using Cosmology: {cosmology.name}."
)
citation = "Jones …
```
> Functionality to display lower and upper limits of observational data

- velociraptor/swift/swift.py
Adds cosmology annotations to a couple of arrays when interfacing with swiftsimio. Otherwise swiftsimio produces some warnings. Doesn't change any behaviour (tested via swiftgalaxy).
> Support for swiftsimio v10

- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/lines.py
The autoplotter allows for a `lower` value to be passed. Currently this removes all datapoints with values smaller than the value of `lower`. This can lead to incorrect percentiles when calculating medians. This PR instead set the value of `lower` as a floor value.
> Set upper/lower as ceiling/floor
