SWIFTSIM/velociraptor-python

- velociraptor/tools/lines.py
- velociraptor/tools/mass_functions.py
Makes `minimum_in_bin` a standard parameter for all lines.
> Make minimum_in_bin a standard parameter for all lines

- velociraptor-plot
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/objects.py
- velociraptor/autoplotter/plot.py
- velociraptor/tools/histogram.py
Adds histogram plots as an actual feature.
> Add histograms

- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/plot.py
- velociraptor/tools/lines.py
Any comments are very welcome :)
> Autoplotter: output data points that were not used to compute median or mean lines

- velociraptor/autoplotter/lines.py
Tiny improvement: we always want to keep track of the units of additional data points
> Additional data points in comparison plots

- docs/source/plotting_tools/index.rst
- examples/auto_plotter.py
- examples/auto_plotter_example.yml
- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/objects.py
- velociraptor/autoplotter/plot.py
- velociraptor/tools/mass_functions.py
Adds the adaptive mass function functionality described in the attached PDF.
[mass_function_calculation_tests.pdf](https://github.com/SWIFTSIM/velociraptor-python/files/5141102/mass_function_calculation_tests.pdf)
> Added adaptive mass functions

- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/compare.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/objects.py
- velociraptor/autoplotter/plot.py
Major update, required for the new pipeline to be usable.
> Observational data directory

- velociraptor/catalogue/registration.py
add dust registration functionality
> add dust registration

- examples/auto_plotter_example.yml
- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/objects.py
- velociraptor/tools/adaptive.py
Adds adaptive binning for mean and median lines
> Adds adaptive binning

- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/lines.py
- velociraptor/autoplotter/metadata.py
- velociraptor/autoplotter/objects.py
- velociraptor/tools/histogram.py
Example
**Non-cumulative**
**Cumulative**
> New feature: cumulative histogram

- velociraptor/autoplotter/compare.py
- velociraptor/autoplotter/objects.py
This should enable comparisons to be made if one simulation is 'missing' the data too.
> Allow comparson plotting if line data is not available

- docs/source/observational_data/creating_data.rst
- docs/source/observational_data/using_data.rst
- tests/test_observational_data.py
- velociraptor/autoplotter/__init__.py
- velociraptor/autoplotter/compare.py
- velociraptor/autoplotter/objects.py
- velociraptor/exceptions.py
- velociraptor/observations/__init__.py
- velociraptor/observations/objects.py
This pull request includes support for Multi-Z datasets and functions to automatically select the correct data.
Note that it deprecates the `load_observation` function to use the `load_observations` function with automatic redshift bracketing instead.
> Multiple Redshift Data

- velociraptor/tools/lines.py
We have decided to make bin centers be computed as the medians of the data points inside the bins 
**Result:** [LINK](http://swift.dur.ac.uk/COLIBREPlots/chaikin/individual_runs/DEC2020/L006N188/NO_EOS/z0.0_2E51_FKIN03_VKICK050_BOOST01/)
> Compute bin centers as medians of the data points

- velociraptor/catalogue/registration.py
Add registration for the field "SNII thermal feedback density"
> Add registration for the field "SNII thermal feedback density"

- velociraptor/catalogue/registration.py
> Register the H, HI, HII, H2, O/H * mass, Fe/H * mass, He, and dust masses

- velociraptor/catalogue/registration.py
to accompany pre-processed fields added in https://gitlab.cosma.dur.ac.uk/EAGLE/swift-colibre/-/merge_requests/167
> Depletion in apertures

- velociraptor/catalogue/registration.py
Does what it says on the tin. 
Example files:
- `/cosma7/data/dp004/jlvc76/SWIFT/master/swiftsim/examples/EAGLE_ICs/EAGLE_25/eagle_0036.hdf5` 
- `/cosma7/data/dp004/jlvc76/SWIFT/master/swiftsim/examples/EAGLE_ICs/EAGLE_25/halos_0036.properties.0`
> Register the stellar luminosities

- velociraptor/catalogue/registration.py
To be merged when SWIFT's https://gitlab.cosma.dur.ac.uk/swift/swiftsim/-/merge_requests/1359 is merged.
> Update the registration of the luminosity bands for the new Nx9 table provided by SWIFT and VR

- velociraptor/catalogue/registration.py
following https://gitlab.cosma.dur.ac.uk/EAGLE/swift-colibre/-/merge_requests/168;
@EvgeniiChaikin 
- pickup **log** mass weighted abundance ratios with high and low floor values
> Pickup floored abundance ratios

- velociraptor/catalogue/catalogue.py
As requested in #74, this adds a convenience mask for centrals and satellites to the catalogue. It's not very pretty, but it does the job.
> Added mask for centrals and satellites to the catalogue.

- velociraptor/particles/particles.py
Addresses #80 - could potentially be cleaner, but perhaps this is enough.
> Hackish fix to be able to load last halo.

- docs/source/conf.py
- examples/auto_plotter.py
- examples/swift_integration.py
- format.sh
- tests/test_observational_data.py
- velociraptor/__init__.py
- velociraptor/autoplotter/objects.py
- velociraptor/catalogue/catalogue.py
- velociraptor/catalogue/registration.py
- velociraptor/particles/particles.py
- velociraptor/swift/swift.py
- velociraptor/tools/adaptive.py
- velociraptor/tools/mass_functions.py
- velociraptor/units.py
Contrary to all the other repositories, this one did not have a formatting script. So I added one.
I will set up CI that checks the formatting once this has been merged.
> Added and applied formatting script.

- velociraptor/__init__.py
- velociraptor/catalogue/catalogue.py
- velociraptor/catalogue/derived.py
Make it possible to pass a list of registration files rather than a single registration file to `load()`.
> Added support for multiple registration files.

- setup.py
- velociraptor/catalogue/registration.py
- velociraptor/catalogue/translator.py
This PR includes the registration of carbon and nitrogen abundances from SOAP into the catalogue. It also suggests a minor change in setup.py due to error when installing the editable veloraptor-python.
> Adding SOAP registration of carbon and nitrogen abundances (PR ready to be reviewed)

- velociraptor/catalogue/translator.py
This PR follows https://github.com/SWIFTSIM/SOAP/pull/61
> Register stellar birth temperature fields in translator.py
